In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/archive (2).zip")

print("Dataset loaded successfully")
print(df.shape)

Dataset loaded successfully
(1000, 28)

In [ ]:
df.head()

,Timestamp,Parking_Spot_ID,Sensor_Reading_Proximity,Sensor_Reading_Pressure,Vehicle_Type_Weight,Vehicle_Type_Height,User_Type,Weather_Temperature,Weather_Precipitation,Nearby_Traffic_Level,...,Occupancy_Status,Vehicle_Type,Parking_Violation,Sensor_Reading_Ultrasonic,Parking_Duration,Environmental_Noise_Level,Dynamic_Pricing_Factor,Spot_Size,Proximity_To_Exit,User_Parking_History
0,2021-01-01 00:00:00.000000000,20,1.023651,1.541461,1831.770127,4.392528,Visitor,18.092553,1,Low,...,Occupied,Car,0,102.951052,4,55.620740,0.8,Standard,6.610474,6.660310
1,2021-01-02 06:39:16.756756756,49,3.903349,1.621719,1330.815754,4.595638,Registered,13.397533,0,Low,...,Occupied,Car,0,87.559131,3,56.682386,1.2,Compact,8.678719,6.766187
2,2021-01-03 13:18:33.513513513,38,10.315709,6.292374,1255.134827,4.313721,Registered,21.687410,0,High,...,Vacant,Car,1,100.061854,5,59.239322,0.8,Standard,13.795262,-0.910052
3,2021-01-04 19:57:50.270270270,31,6.588039,1.659870,1523.442919,3.567329,Visitor,18.683461,0,Medium,...,Vacant,Motorcycle,1,110.594598,2,44.545155,0.8,Standard,1.678721,10.415888
4,2021-01-06 02:37:07.027027027,8,8.213969,3.278467,1758.490837,5.145836,Visitor,19.214876,0,High,...,Occupied,Car,0,84.786963,2,48.012604,0.8,Standard,20.012252,4.355544

In [ ]:
df.columns.tolist()

['Timestamp',
 'Parking_Spot_ID',
 'Sensor_Reading_Proximity',
 'Sensor_Reading_Pressure',
 'Vehicle_Type_Weight',
 'Vehicle_Type_Height',
 'User_Type',
 'Weather_Temperature',
 'Weather_Precipitation',
 'Nearby_Traffic_Level',
 'Entry_Time',
 'Exit_Time',
 'Electric_Vehicle',
 'Reserved_Status',
 'Occupancy_Rate',
 'Payment_Amount',
 'Parking_Lot_Section',
 'Payment_Status',
 'Occupancy_Status',
 'Vehicle_Type',
 'Parking_Violation',
 'Sensor_Reading_Ultrasonic',
 'Parking_Duration',
 'Environmental_Noise_Level',
 'Dynamic_Pricing_Factor',
 'Spot_Size',
 'Proximity_To_Exit',
 'User_Parking_History']

In [ ]:
df.isnull().sum()

Timestamp                    0
Parking_Spot_ID              0
Sensor_Reading_Proximity     0
Sensor_Reading_Pressure      0
Vehicle_Type_Weight          0
Vehicle_Type_Height          0
User_Type                    0
Weather_Temperature          0
Weather_Precipitation        0
Nearby_Traffic_Level         0
Entry_Time                   0
Exit_Time                    0
Electric_Vehicle             0
Reserved_Status              0
Occupancy_Rate               0
Payment_Amount               0
Parking_Lot_Section          0
Payment_Status               0
Occupancy_Status             0
Vehicle_Type                 0
Parking_Violation            0
Sensor_Reading_Ultrasonic    0
Parking_Duration             0
Environmental_Noise_Level    0
Dynamic_Pricing_Factor       0
Spot_Size                    0
Proximity_To_Exit            0
User_Parking_History         0
dtype: int64

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
df = df.drop_duplicates()

print("Duplicates after cleaning:", df.duplicated().sum())

Duplicates after cleaning: 0

In [ ]:
df.columns = df.columns.str.strip()

print("Column names cleaned")

Column names cleaned

In [ ]:
df.dtypes

Timestamp                     object
Parking_Spot_ID                int64
Sensor_Reading_Proximity     float64
Sensor_Reading_Pressure      float64
Vehicle_Type_Weight          float64
Vehicle_Type_Height          float64
User_Type                     object
Weather_Temperature          float64
Weather_Precipitation          int64
Nearby_Traffic_Level          object
Entry_Time                     int64
Exit_Time                      int64
Electric_Vehicle               int64
Reserved_Status                int64
Occupancy_Rate               float64
Payment_Amount               float64
Parking_Lot_Section           object
Payment_Status                object
Occupancy_Status              object
Vehicle_Type                  object
Parking_Violation              int64
Sensor_Reading_Ultrasonic    float64
Parking_Duration               int64
Environmental_Noise_Level    float64
Dynamic_Pricing_Factor       float64
Spot_Size                     object
Proximity_To_Exit            float64
User_Parking_History         float64
dtype: object

In [ ]:
df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    errors="coerce"
)

print("Timestamp converted successfully")

Timestamp converted successfully

In [ ]:
num_cols = df.select_dtypes(include=np.number).columns

df[num_cols] = df[num_cols].fillna(
    df[num_cols].median()
)

print("Numerical missing values handled")

Numerical missing values handled

In [ ]:
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

print("Categorical missing values handled")

Categorical missing values handled

In [ ]:
for col in cat_cols:
    df[col] = df[col].str.strip()

print("Extra spaces removed")

Extra spaces removed

In [ ]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Missing values: 0
Duplicate rows: 0

In [ ]:
print("Final Dataset Shape:", df.shape)

df.head()

Final Dataset Shape: (1000, 28)

,Timestamp,Parking_Spot_ID,Sensor_Reading_Proximity,Sensor_Reading_Pressure,Vehicle_Type_Weight,Vehicle_Type_Height,User_Type,Weather_Temperature,Weather_Precipitation,Nearby_Traffic_Level,...,Occupancy_Status,Vehicle_Type,Parking_Violation,Sensor_Reading_Ultrasonic,Parking_Duration,Environmental_Noise_Level,Dynamic_Pricing_Factor,Spot_Size,Proximity_To_Exit,User_Parking_History
0,2021-01-01 00:00:00.000000000,20,1.023651,1.541461,1831.770127,4.392528,Visitor,18.092553,1,Low,...,Occupied,Car,0,102.951052,4,55.620740,0.8,Standard,6.610474,6.660310
1,2021-01-02 06:39:16.756756756,49,3.903349,1.621719,1330.815754,4.595638,Registered,13.397533,0,Low,...,Occupied,Car,0,87.559131,3,56.682386,1.2,Compact,8.678719,6.766187
2,2021-01-03 13:18:33.513513513,38,10.315709,6.292374,1255.134827,4.313721,Registered,21.687410,0,High,...,Vacant,Car,1,100.061854,5,59.239322,0.8,Standard,13.795262,-0.910052
3,2021-01-04 19:57:50.270270270,31,6.588039,1.659870,1523.442919,3.567329,Visitor,18.683461,0,Medium,...,Vacant,Motorcycle,1,110.594598,2,44.545155,0.8,Standard,1.678721,10.415888
4,2021-01-06 02:37:07.027027027,8,8.213969,3.278467,1758.490837,5.145836,Visitor,19.214876,0,High,...,Occupied,Car,0,84.786963,2,48.012604,0.8,Standard,20.012252,4.355544

In [ ]:
df.to_csv(
    "Cleaned_Smart_Parking_Dataset.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
from google.colab import files

files.download("Cleaned_Smart_Parking_Dataset.csv")